name: node
type: nodejs:10

dependencies:
  nodejs:
    pm2: "^2.0.0"

web:
  commands:
    start: "PM2_HOME=$PLATFORM_APP_DIR/run pm2 start bin/www --no-daemon"

mounts:
  "/run": "shared:files/run"

disk: 512

relationships:
    database: "featuresdb:mongodb"

variables:
  env:
    PLATFORMSH_ENV: true